name: Build and Deploy BugBuster

on:
  push:
    branches:
      - master
    paths:
      - 'bots/bugbuster/**'
  pull_request:
    paths:
      - 'bots/bugbuster/**'
  workflow_dispatch: {}

defaults:
  run:
    working-directory: ./bots/bugbuster

jobs:
  bugbuster:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Setup Tilt
        uses: ./.github/actions/setup-tilt
        with:
          tilt_cmd: 'build-packages'
      - name: Install NPM Dependencies
        run: pnpm install
      - name: Login to Botpress
        run: pnpm bp login -y --token ${{ secrets.PRODUCTION_TOKEN_CLOUD_OPS_ACCOUNT }} --workspace-id ${{ secrets.PRODUCTION_CLOUD_OPS_WORKSPACE_ID }}
      - name: Install Botpress Dependencies
        run: pnpm bp add linear -y && pnpm bp add github -y && pnpm bp add slack
      - name: Type Check
        run: tsc --noEmit
      - name: Build
        run: pnpm bp build -y
      - name: Deploy
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          root_dir="$(pwd)/../.."
          script_path="$root_dir/.github/scripts/get-or-create-bot.sh"
          botid=$($script_path bugbuster)
          pnpm bp deploy --botId $botid -y
