name: 'Check PR'
on:
  pull_request:
    types: [synchronize, edited, review_requested, ready_for_review]
jobs:
  check-pr:
    name: Asserts PR is in shape
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.1'
      - name: Assert PR
        id: assert_pr
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_request: ${{ toJson(github.event.pull_request) }}
        run: |
          npm install @actions/core @actions/github
          node .github/workflows/code/check-pr/index.js
