name: Codestyle
on: [push]
jobs:
  run_prettier:
    name: Run Prettier on codebase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        yarn
    - name: Run Prettier
      run: |
        ./node_modules/prettier/bin-prettier.js --check --write '{src,modules}/**/*.ts' '!**/*.d.ts'
