name: Release Binaries
on:
  pull_request:
    types: [review_requested]
  release:
    types: [published]
permissions:
  contents: read

jobs:
  release_bin:
    # Do not publish dependabot branches
    if: startsWith(github.head_ref, 'dependabot/') != true

    name: Build and Publish Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Configure SSH Key
        uses: botpress/gh-actions/set_ssh_key@v1
        with:
          ssh_key: ${{ secrets.BP_PRO_SSH }}

      - name: Install python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Tools
        run: pip install awscli

      - name: Build Project
        run: |
          yarn
          yarn build --prod
        env:
          EDITION: pro
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Archives
        run: yarn cmd archive

      - name: Rename Binary Files
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'review_requested' }}
        uses: botpress/gh-actions/rename_binaries@v1
        with:
          path: ./packages/bp/archives

      - name: Extract Information
        id: info
        uses: botpress/gh-actions/extract_info@v1

      - name: Publish Dev Binaries
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'review_requested' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync packages/bp/archives s3://botpress-dev-bins/botpress/${{ steps.info.outputs.branch_sanitized }}

      - name: Publish Prod Binaries
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync packages/bp/archives s3://botpress-binaries/
