name: Tests
on: [pull_request]
permissions:
  contents: read

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Fetch Node Packages for module NLU
        working-directory: ./modules/nlu
        run: |
          yarn --frozen-lockfile
      - name: Run tests
        run: |
          yarn test:unit

  integration:
    name: Integration
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Fetch Node Packages for module NLU
        working-directory: ./modules/nlu
        run: |
          yarn --frozen-lockfile
      - name: Run tests
        run: |
          yarn test:int
        env:
          PG_DB: postgres
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_PORT: 5432

  e2e:
    permissions:
      contents: none
    name: E2E (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOTPRESS_BOT_APP_ID }}
          private_key: ${{ secrets.BOTPRESS_BOT_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@master
        with:
          token: ${{ steps.generate-token.outputs.token }}
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Build core, UI and modules
        run: yarn build --prod --linux
        env:
          NODE_OPTIONS: '--max-old-space-size=6000'
          EDITION: pro
      - name: Run Tests
        run: |
          yarn start & 
          yarn test:e2e
        env:
          BP_LICENSE_KEY: ${{ secrets.BP_LICENSE_KEY }}
          BP_CONFIG_PRO_ENABLED: true
          HEADLESS: true
          JEST_TIMEOUT: 30000
      - name: Upload Screenshots
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: screenshots
          path: build/tests/e2e/screenshots
#
# TODO: windows and macos tests are disabled for now since tests
# on windows often fails for network reasons and are flaky on macos
#  e2e-windows:
#    name: E2E (windows-latest)
#    runs-on: windows-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@master
#      - uses: actions/setup-node@v2
#        with:
#          node-version-file: '.nvmrc'
#          cache: 'yarn'
#      - name: Fetch Node Packages
#        run: |
#          yarn --frozen-lockfile
#      - name: Build core, UI and modules
#        run: yarn build
#        env:
#          NODE_OPTIONS: '--max-old-space-size=6000'
#      - name: Run Tests
#        run: |
#          yarn start &
#          yarn test:e2e
#        env:
#          BP_LICENSE_KEY: ${{ secrets.BP_LICENSE_KEY }}
#          BP_CONFIG_PRO_ENABLED: true
#          HEADLESS: true
#          JEST_TIMEOUT: 30000
#      - name: Upload Screenshots
#        uses: actions/upload-artifact@master
#        if: failure()
#        with:
#          name: screenshots
#          path: build/tests/e2e/screenshots
#
#  e2e-macos:
#    name: E2E (macos-latest)
#    runs-on: macos-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@master
#      - uses: actions/setup-node@v2
#        with:
#          node-version-file: '.nvmrc'
#          cache: 'yarn'
#      - name: Fetch Node Packages
#        run: |
#          yarn --frozen-lockfile
#      - name: Build core, UI and modules
#        run: yarn build
#        env:
#          NODE_OPTIONS: '--max-old-space-size=6000'
#      - name: Run Tests
#        run: |
#          yarn start &
#          yarn test:e2e
#        env:
#          BP_LICENSE_KEY: ${{ secrets.BP_LICENSE_KEY }}
#          BP_CONFIG_PRO_ENABLED: true
#          HEADLESS: true
#          JEST_TIMEOUT: 30000
#      - name: Upload Screenshots
#        uses: actions/upload-artifact@master
#        if: failure()
#        with:
#          name: screenshots
#          path: build/tests/e2e/screenshots
